### ISSUE TITLE
Update for 2022

### ISSUE THREAD

**Issue by jpoep** [freestlr/place#1]
Hey,

I have no idea if this project is still on your radar and how the binary input format works, but would it be possible for you to update the project to include the 2022 r/place? It'd be even cooler if there was a way to display live data.

**Comment by Revadike** [comment]
I was wondering the same thing

**Comment by Revadike** [comment]
Seems it loads the data from https://freestlr.github.io/place/data/out.bin
So, in theory, we just have to update this data.

**Comment by rissson** [comment]
I'm looking into updating data.bin, and looking at https://github.com/freestlr/place/blob/master/data/compress.pl, and I must say, oh god.

**Comment by Ghost4Man** [comment]
I don't have any experience with Perl and I couldn't get the script to run properly, so I tried to convert it into Python, but it's not producing the right results. I don't currently have much time to investigate why. Maybe someone could use it as a starting point: https://gist.github.com/Ghost4Man/f7dae8704f3e89f913cf9d8287a77842

**Comment by firekeeper-anna** [comment]
It appears that @freestlr used the official reddit dump from 2017 for this project. (see https://www.reddit.com/r/dataisbeautiful/comments/66ivqs/interactive_timelapse_of_rplace_oc/).
If they release a dump again this year, they'll progrably do it in the linked subreddit.

I'd be very interested to see this come to live and help if possible.

**Comment by Revadike** [comment]
Keep an eye on https://www.reddit.com/user/Drunken_Economist/

**Comment by codetheweb** [comment]
The full dataset was posted: https://www.reddit.com/r/place/comments/txvk2d/rplace_datasets_april_fools_2022/

**Comment by jpoep** [comment]
The current binary format won't work for the 2022 version anymore. Here's @freestlr's [reddit comment from 2017](https://www.reddit.com/r/dataisbeautiful/comments/66ivqs/comment/dgisanh/?utm_source=share&utm_medium=web2x&context=3) that explains how the binary format works: 

> I've taken final csv dataset from https://np.reddit.com/r/redditdata/comments/6640ru/place_datasets_april_fools_2017/ that contains 16.5M pixel hits in format timestamp, user_hash, x, y, color

>that was about 830MB - too big to send around web. Also, including about 3500 hits at (1000,), (,1000) and (1000,1000) points outside of [0,999] range.

>Then I decided to drop time and user information, leaving only x, y and color in order of appearance. and we have a 1000x1000 canvas and 16 colors, so every hit almost perfectly fit in 3 bytes: 10 bits for x + 10 bits for y + 4 bits for color, resulting in ~50MB binary file

Given that this year's canvas is four times as big and there are more colors, we now need 11 bits for coordinates and 5 bits for color. The canvas is 2000x2000 and there are 19 colors if I'm not mistaken. 

It shouldn't be too hard to implement these changes, but it's still more than just creating a new binary dump.

Also, the dump is going to be much bigger. In 2017, the conversion to binary shrank the CSV data from about 830 MB to 50 MB. Assuming the ratio stays the same, this year's ~19.5 GB will still be roughly 1.17 GB after the conversion, which all needs to be fetched by the users' browsers. Maybe it should be split into chunks that are lazily loaded?

**Comment by firekeeper-anna** [comment]
Thank you @qelix for your insights and rough approximations on the file size. I started working on converting the dataset and your comment helped a lot already.
I'll probably submit a pull request when I have a meaningful result.

**Comment by firekeeper-anna** [comment]
I've been able to convert the new data into a compressed binary file with the same format but more bits, exactly as @qelix proposed. I've had to edit the code to parse the binary data, which to be honest was a pretty tricky for me.
Thankfully @freestlr's code was very easy to understand.

I've upgraded from three bytes to four bytes. This means 5 bits are unused per pixel/hit. This surely could be optimized but was out of my scope for now. The file is 617 MB now.
Unfortunately I can't upload the file as one big chunk. I'll have to split it into 7 files smaller than 100MB. 
I'll try to figure this out tomorrow. (see here: https://github.com/TomRiddle01/place/tree/place2022)

The download-time will probably be pretty significant but locally it works flawless.
I'm astounished by the performance of this implementation as it scales to the much larger /r/place without issues.

Also I'm ignoring the censored rectangles that were placed by reddit mods. A result of this might be that the inapproriate _art_ is visible on more frames. Implementing the rectangles would be tricky.

**Comment by jpoep** [comment]
Thanks so much for your work, @TomRiddle01!  I think hat once the chunking problem is solved, we should probably add a warning, especially for mobile users whose data plan is about to be annihilated, and then consider this issue done. 

Maybe there's a way to just stream the data that is needed at any given moment, but it sounds rather complicated and not as easily doable without a proper server? 

As @freestlr seems to have vanished, I guess that your repo will be the main fork pretty soon.

Also, I think it's way better that the censored rectangles aren't shown, I wouldn't wanna change that.

**Comment by firekeeper-anna** [comment]
I've been thinking about the streaming idea too. A big problem is, that it ruins the smooth experience when moving the slider back and forth through the full timeline.
We might be able to add something like key-frames or i-frames as used in video encoding that are pre-loaded for that.
This is way more complex though and probably requires lots of refactoring.

I guess I'm okay with working in my fork for now until @freestlr resurfaces.

**Comment by jpoep** [comment]
Nevermind, maybe you could check out https://git-lfs.github.com/, @TomRiddle01. I've never used it myself, but GitHub seems to support files larger than 100mb with it.

Edit: I sent that before your last comment, and yeah, you're probably right on the streaming part.

**Comment by firekeeper-anna** [comment]
I've never used it either but my short googling seemed like LFS might not work with github-pages, unfortunately.

I've created another issue in my repo. Also I've implemented the chunks and published the (hopefully) working version here:
https://tomriddle01.github.io/place/ (600MB Download starts immediately)

Please report back if there are any issues

**Comment by Revadike** [comment]
`GET https://tomriddle01.github.io/favicon.ico 404`

You said *any* issues :)

**Comment by Revadike** [comment]
For me, it ends at time 158117487
![image](https://user-images.githubusercontent.com/4411977/162547920-a91ac04d-e1c2-4844-a406-8bb8637183a9.png)

Shouldn't there be a bit more after?

**Comment by rissson** [comment]
Someone also hacked this here: https://place2022.nyaaori.cat/, but it _only_ takes 516 MB

**Comment by Revadike** [comment]
@placeAtlas I saw you forked this repo recently. Be sure to check out the great work above! Bedankt voor het maken van de atlas :)

**Comment by firekeeper-anna** [comment]
It ends on the same frame for me. Compared to the other updated version @rissson posted above my animation indeed ends early.

**Comment by firekeeper-anna** [comment]
I added the missing data. It should work not to the very end @Revadike

**Comment by freestlr** [comment]
Hi guys. I've made an update with 2022 data, so you can check it by the gh pages link: https://freestlr.github.io/place/?d=2022

Well, that was a bit harder than the previous event. The number of points raised 10 times from 16M to 160M, as well as the board size and colors, giving us 27 bits per pixel at the end. So, the packed data takes about 516MB.

But, there are two split points actually: the first one unlocks the range [1000,2000) for the x, and second do the same for the y.
So, I've split the data into 3 parts - 25bpp before the first split, 26bpp before the second, and 27bpp afterwards. That gives a ~12MB bonus savings :)

Also, had to split the chunks event more, as gh forces to use files less than 100MB, and recommends 50MB limit. And with lazy loading you have to wait only for first 50MB to see the picture.

And thanks all of you! I didn't even know about reddit have resurrected r/place this year.

**Comment by firekeeper-anna** [comment]
Ohhh very nice @freestlr! I like the lazy loading progress in the timeline! I guess I don't need to continue optimizing my hacky code then. I'll probably forward my fork to yours though as I was planning to add some stuff for myself.

**Comment by jpoep** [comment]
Thanks for the update, @freestlr, looks good ❤️

And of course thanks to all the others as as well, even though @freestlr just obsoleted everyone's work all of a sudden 😁
